image: maven:latest

build:
  script: "mvn clean package -pl 'Pucman Common':'Pucman Bungee' -am"
  artifacts:
     paths:
       - "Pucman Server/target/*.jar"
       - "Pucman Common/target/*.jar"
       - "Pucman Bungee/target/*.jar"
