image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode -X"
  MAVEN_OPS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - ".m2/repository/"
    - "target/"

build:
  stage: build
  script:
    - "mvn $MAVEN_CLI_OPS package"

test:
  stage: test
  script:
    - "mvn $MAVEN_CLI_OPS test"

deploy:
  stage: deploy
  script:
    - "mvn $MAVEN_CLI_OPTS deploy"
  only:
    - "master"