language: java
sudo: required

jdk:
  - openjdk8
  - openjdk9

before_install:
  - git config --global user.email "travis-ci@travis-ci.org"
  - git config --global user.name "Travis CI"

branches:
  only: master

cache:
  directories:
    - '$HOME/.m2/repository'

script: mvn clean package --settings ~/.m2/settings.xml
after_success: mvn clean deploy --settings ~/.m2/settings.xml