language: java
sudo: required

jdk:
  - openjdk8
  - openjdk9

env:
  global:
    - SONATYPE_USERNAME=admin
    - secure: "your encrypted SONATYPE_PASSWORD=WhitePanda1819"

before_install:
  - git config --global user.email "travis-ci@travis-ci.org"
  - git config --global user.name "Travis CI"

branches:
  only: master

cache:
  directories:
    - '$HOME/.m2/repository'

script: mvn clean package
after_success: mvn clean deploy --settings ~/.m2/settings.xml